version: '3.8'

services:
  postgis:
    build:
      context: ./.config/postgis 
    image: exspda_postgis:13-3.0-3.12
    container_name: exspda_postgis
    env_file: 
      - ./.config/postgis/postgis.env 
    volumes: 
      - exspda_postgis_data:/var/lib/postgresql/data:Z
      - ./local_data/geospatial:/work
    hostname: exspda_postgis
    networks:
      - exspda_network
    ports: 
      - 5555:5432

  pgadmin:
    build:
      context: ./.config/pgadmin4
    image: exspda_pgadmin4
    container_name: exspda_pgadmin4
    env_file: 
      - ./.config/pgadmin4/pgadmin.env
    volumes: 
      - exspda_pgadmin4:/var/lib/pgadmin
      # - ./local_data/pgadmin:/work
    depends_on:
      - postgis
    hostname: exspda_pgadmin4
    networks: 
      - exspda_network
    ports: 
      - 5050:80

  tileserver:
    build: 
      context: .
      dockerfile: ./.config/pg_tileserv/Dockerfile
    image: exspda_pg_tileserv
    container_name: exspda_pg_tileserv
    env_file: 
      - ./.config/pg_serv.env
    depends_on:
      - postgis
    hostname: exspda_pg_tileserv
    networks: 
      - exspda_network
    ports: 
      - 7800:7800

  featureserver:
    build: 
      context: .
      dockerfile: ./.config/pg_featureserv/Dockerfile
    image: exspda_pg_featureserv
    container_name: exspda_pg_featureserv
    env_file: 
      - ./.config/pg_serv.env
    depends_on:
      - postgis
    hostname: exspda_pg_featureserv
    networks: 
      - exspda_network
    ports: 
      - 9000:9000

networks: 
  exspda_network:

volumes: 
  exspda_postgis_data:
  exspda_pgadmin4:
